try fix

diff --git a/.github/workflows/avd-kernel.yml b/.github/workflows/avd-kernel.yml
--- a/.github/workflows/avd-kernel.yml
+++ b/.github/workflows/avd-kernel.yml
@@ -119,7 +119,7 @@ jobs:
             export KSU_EXPECTED_SIZE=${{ vars.EXPECTED_SIZE }}
             export KSU_EXPECTED_HASH=${{ vars.EXPECTED_HASH }}
           fi
-          tools/bazel run --config=android_ci --config=stamp --lto=thin --verbose_failures //common-modules/virtual-device:virtual_device_${{ inputs.arch }}_dist -- --dist_dir=dist || echo "Build failed? ignore"
+          tools/bazel run --config=fast --config=stamp --lto=thin --verbose_failures --sandbox_debug //common-modules/virtual-device:virtual_device_${{ inputs.arch }}_dist -- --dist_dir=dist || echo "Build failed? ignore"
           NAME=kernel-${{ inputs.arch }}-avd-${{ inputs.version_name }}-${{ env.kernelsu_version }}
           TARGET_IMAGE=dist/bzImage
           if [ ! -e $TARGET_IMAGE ]; then
